#!/bin/sh

PEM=$1
if [ -z "$PEM" ];then
  PEM="~/.ssh/xpeppers/discourse.pem"
fi

ansible discourse -i inventory/aws_hosts --private-key "$PEM" -u ubuntu -m command -a "sudo /var/discourse/launcher logs app"
