#!/bin/sh

set -e

PEM=$1
if [ -z "$PEM" ];then
  PEM="~/.ssh/xpeppers/discourse.pem"
fi

# discourse_up_to_date=$(cd playbooks/roles/discourse/files/discourse; git status -uno | grep up-to-date)
# if [[ $discourse_up_to_date = "Your branch is up-to-date with 'origin/master'." ]]
# then
#   echo "Discourse is up to date, let's do this!"
# else
#   echo "Please update the discourse source..."
#   echo "'git pull' in 'playbooks/roles/discourse/files/discourse'"
#   exit 1
# fi


ansible-playbook playbooks/main.yml\
  -i inventory/aws_hosts\
  --private-key "$PEM"\
  -u ubuntu\
  -vvvv
