#!/bin/sh

set -e

PEM=$1
if [ -z "$PEM" ];then
  PEM="~/.ssh/xpeppers/discourse.pem"
fi

ansible-playbook playbooks/only_machine.yml\
  -i inventory/aws_hosts\
  --private-key "$PEM"\
  -u ubuntu\
  -vvvv
